### ISSUE TITLE
Feature request: add sms and call logs backup and restore

### ISSUE THREAD

**Issue by thewh1teagle** [mrrfv/open-android-backup#23]
I think that it's a key feature to have the ability to backup sms and call logs, 
Every time I backup my phone for me or for someone else I saw that it's important to keep old sms messages and call logs.

**Comment by mrrfv** [comment]
I doubt that this is even possible, as Android is pretty locked down these days and the reason your phone manufacturer's app can restore SMS messages is because it has special privileges to do so. The only possible way I think this could be implemented is adding a "backup viewer" to the companion app, which would allow you to view the message history when it's needed.

**Comment by thewh1teagle** [comment]
Of course it's possible
Try this app, it works for sms and call logs - backup and restore
https://play.google.com/store/apps/details?id=com.idea.backup.smscontacts

**Comment by IntoTheVoid-900** [comment]
Is this planned? Right now I am using Simple SMS messenger to manually backup SMS files and then adding it to the backup archive.

**Comment by mrrfv** [comment]
Planned, but it'll take a while before it's implemented. I don't know how to make this using Flutter at the moment.

**Comment by mrrfv** [comment]
SMS and call logs backups have been added in the latest commit, currently cannot be restored to a new device though.

**Comment by IntoTheVoid-900** [comment]
Awesome, thanks!
